### ISSUE TITLE
Build fails when using Vite Legacy plugin

### ISSUE THREAD

**Issue by christowiz** [jiangfengming/svelte-pilot#2]
Apps throw an error after building using the Vite Legacy plugin.

<img width="755" alt="image" src="https://github.com/svelte-pilot/svelte-pilot/assets/597282/b6522a1d-b4da-4aa5-ab55-e4e4c79bc246">
<img width="906" alt="image" src="https://github.com/svelte-pilot/svelte-pilot/assets/597282/f65e5942-bdd6-4e24-900e-5ea7c77273d5">

I have created a simple example by cloning the Svelte Pilot Template repository and adding an additional Vite config file (`vite.legacy.config.ts`).

[https://github.com/christowiz/svelte-pilot-legacy](https://github.com/christowiz/svelte-pilot-legacy)

**Comment by jiangfengming** [comment]
Fixed in https://github.com/svelte-pilot/svelte-pilot/commit/fd7d175e0ced6807f4f4b02aede17e0cd5615f2f
