### ISSUE TITLE
how to start with svelte5

### ISSUE THREAD

**Issue by cu1desac** [jiangfengming/svelte-pilot#3]
I follow your guid [(url)](https://svelte-pilot.github.io/en/creating-a-project),but it does not work in online IDE.  SSR Template works well, but i want to use this router with tauri+svelte. Please!
![微信截图_20241120220808](https://github.com/user-attachments/assets/01a6273b-ca59-4f56-a57c-d507c1427a3f)

**Comment by cu1desac** [comment]
i resolved. but i dont confirm if it's the right way to use this router.
![微信截图_20241121221205](https://github.com/user-attachments/assets/0127a324-0851-4aa9-9949-cec31c92a486)

**Comment by jiangfengming** [comment]
Because the documentation has not yet been updated for the `mount()` function in Svelte 5. Please call `mount()` inside `router.start(onReady)`:

```js
import './app.css';
import { mount } from 'svelte';
import { ClientApp } from 'svelte-pilot';
import router from './router';

router.start(() =>
  mount(ClientApp, {
    target: document.getElementById('app'),
    props: { router },
  })
);
```

**Comment by cu1desac** [comment]
Thank you, my hero!!

**Comment by jiangfengming** [comment]
The document has been updated. Feel free to raise an issue if you encounter any problems.
